// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIVZ2yyPop0sty5GHSxbaObg_vzm8IvHs',
    appId: '1:356684089267:web:fc79db8a4734eb9181adc6',
    messagingSenderId: '356684089267',
    projectId: 'urbanstop-monitoring',
    authDomain: 'urbanstop-monitoring.firebaseapp.com',
    databaseURL: 'https://urbanstop-monitoring-default-rtdb.firebaseio.com',
    storageBucket: 'urbanstop-monitoring.firebasestorage.app',
    measurementId: 'G-85BCXWM7BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXY4ac4Tiwu5jgryYHXeOJNFKKtM7uayo',
    appId: '1:356684089267:android:bdcee9b5a020d50c81adc6',
    messagingSenderId: '356684089267',
    projectId: 'urbanstop-monitoring',
    databaseURL: 'https://urbanstop-monitoring-default-rtdb.firebaseio.com',
    storageBucket: 'urbanstop-monitoring.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIVZ2yyPop0sty5GHSxbaObg_vzm8IvHs',
    appId: '1:356684089267:web:68b15c1180dbffb681adc6',
    messagingSenderId: '356684089267',
    projectId: 'urbanstop-monitoring',
    authDomain: 'urbanstop-monitoring.firebaseapp.com',
    databaseURL: 'https://urbanstop-monitoring-default-rtdb.firebaseio.com',
    storageBucket: 'urbanstop-monitoring.firebasestorage.app',
    measurementId: 'G-0NXV99MB1J',
  );

}